### ISSUE TITLE
doesnt change username

### ISSUE THREAD

**Issue by yxshi4** [r6f/TikTok-AutoClaimer#1]
It's actually really cool but i tested it and it didnt change the username it was an error.

**Comment by r6f** [comment]
well, you can´t change username if you already changed it less than 30 days or your ip is limited. I suggest trying it again on other account or using a fresh new ip

**Comment by ItroublveTSCV8** [comment]
how do i login

> how is it sus? how do you wanna change your username without logging in? LOL
